# Generated by Django 3.2.6 on 2021-08-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
                ('payment_term', models.CharField(max_length=45)),
                ('delivery_fee', models.CharField(max_length=45)),
                ('free_delivery', models.IntegerField()),
                ('free_delivery_condition', models.CharField(blank=True, max_length=45, null=True)),
                ('time_record', models.DateTimeField()),
                ('shipping_term', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdersDetail',
            fields=[
                ('order_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'orders_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=45)),
                ('product_bid', models.IntegerField()),
                ('inventory', models.IntegerField()),
                ('quantity_sold', models.IntegerField()),
                ('product_category', models.CharField(max_length=45)),
                ('product_type', models.CharField(max_length=45)),
                ('price', models.IntegerField()),
                ('product_color', models.CharField(max_length=45)),
                ('preorder', models.IntegerField()),
                ('discount', models.FloatField()),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_type', models.CharField(blank=True, max_length=45, null=True)),
                ('question_number', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Streamings',
            fields=[
                ('streaming_id', models.AutoField(primary_key=True, serialize=False)),
                ('streaming_name', models.CharField(max_length=45)),
                ('likes', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('shares', models.IntegerField()),
            ],
            options={
                'db_table': 'streamings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StreamingsDetail',
            fields=[
                ('streaming_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_amount', models.IntegerField()),
                ('views', models.IntegerField()),
                ('time_record', models.DateTimeField()),
            ],
            options={
                'db_table': 'streamings_detail',
                'managed': False,
            },
        ),
    ]
