# Generated by Django 3.2.7 on 2021-09-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemp',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('text', models.TextField(blank=True, null=True)),
                ('time_stamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'message_temp',
                'managed': False,
            },
        ),
    ]
