# Generated by Django 3.2.7 on 2021-10-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MessageTemp',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('text', models.TextField(blank=True, null=True)),
                ('datetime', models.DateTimeField()),
                ('intents', models.CharField(blank=True, max_length=20, null=True)),
                ('entities', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'message_temp',
                'managed': False,
            },
        ),
    ]
