# Generated by Django 3.2.7 on 2021-10-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_djangomigrations_messagetemp'),
        ('trips', '0002_messagetemp'),
    ]

    operations = [
    ]
